#!/bin/bash


deploy_mqsc() {

  cat <<EOF | oc create -n integration-enablement -f -
  kind: ConfigMap
  apiVersion: v1
  metadata:
    name: enablement-mqsc
  data:
    mq.mqsc: |-
      DEFINE CHANNEL('DIGITAL') CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH (OPTIONAL) REPLACE
      ALTER AUTHINFO(SYSTEM.DEFAULT.AUTHINFO.IDPWOS) AUTHTYPE(IDPWOS) CHCKCLNT(OPTIONAL)
      ALTER QMGR CHLAUTH(DISABLED)
      REFRESH SECURITY TYPE(CONNAUTH)
      DEFINE QLOCAL('TRANSFER.REQUEST.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
      DEFINE QLOCAL('TRANSFER.RESPONSE.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
      DEFINE QLOCAL('BALANCE.REQUEST.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
      DEFINE QLOCAL('BALANCE.RESPONSE.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
      DEFINE QLOCAL('DEBIT.REQUEST.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
      DEFINE QLOCAL('DEBIT.RESPONSE.QUEUE') DEFPRESP(SYNC) DEFPSIST(YES)
EOF
}

deploy_mqsc